services:
  todo_api_name:
    build:
      context: .
      dockerfile: dockerfile.prod
    image: drglasdou/todo_api:${APP_VERSION:-1.0.0}

  todo_api_latest:
    build:
      context: .
      dockerfile: dockerfile.prod
    image: drglasdou/todo_api:latest
